# Generated by Django 4.0.4 on 2022-06-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
