# Generated by Django 4.0.4 on 2022-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_task_taskcomment_tasklike_delete_advert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(),
        ),
    ]
