# Generated by Django 4.0.4 on 2022-06-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_task_user_alter_tasklike_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklike',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasklike',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
        migrations.DeleteModel(
            name='Tasklike',
        ),
    ]
